"""Constants defined for Snake"""

# snake specs constants
SNAKE_FOOD_DISTANCE = 15
SNAKE_PACE = 20
SNAKE_INITIAL_LENGTH = 3
SNAKE_COLOR = "white"

# screen constants
WINDOW_HEIGHT = 600
WINDOW_WIDTH = 600
WINDOW_LIMIT = WINDOW_HEIGHT // 2 - SNAKE_PACE // 2
MAX_X_COOR = WINDOW_LIMIT
MIN_X_COOR = - (WINDOW_LIMIT)
MAX_Y_COOR = WINDOW_LIMIT
MIN_Y_COOR = - (WINDOW_LIMIT)

# navigation constants
UP_DIRECTION = 90
DOWN_DIRECTION = 270
RIGHT_DIRECTION = 0
LEFT_DIRECTION = 180

# food specs
FOOD_SHAPE = "circle"
FOOD_COLOR = "purple"
FOOD_SPEED = 0
FOOD_WINDOW_LIMIT = WINDOW_LIMIT - SNAKE_PACE // 2
FOOD_MAX_X_COOR = FOOD_WINDOW_LIMIT
FOOD_MIN_X_COOR = - (FOOD_WINDOW_LIMIT)
FOOD_MAX_Y_COOR = FOOD_WINDOW_LIMIT
FOOD_MIN_Y_COOR = - (FOOD_WINDOW_LIMIT)

#score file path
HIGHSCORE_PATH = "high_score.txt"


