"""Constants defined for Snake"""

# screen constants
WINDOW_HEIGHT = 600
WINDOW_WIDTH = 600
WINDOW_LIMIT = WINDOW_HEIGHT // 2 - 20
MAX_X_COOR = WINDOW_LIMIT
MIN_X_COOR = - (WINDOW_LIMIT)
MAX_Y_COOR = WINDOW_LIMIT
MIN_Y_COOR = - (WINDOW_LIMIT)

# navigation constants
UP_DIRECTION = 90
DOWN_DIRECTION = 270
RIGHT_DIRECTION = 0
LEFT_DIRECTION = 180

# snake specs constants
# SNAKE_LENGTH = 3
SNAKE_FOOD_DISTANCE = 15
SNAKE_PACE = 20
